### ISSUE TITLE
Congratulations! New release published. And some suggestions.

### ISSUE THREAD

**Issue by Shine0717** [brianch/offline-chess-puzzles#2]
After waiting for a long time, the new version updated. Hurrah!
Thank you very much for your hard work, Brianch!
==========================================================
The new version:
It runs perfectly under win7/10 system.
Display the movement of each step, including the last step of the computer which is very useful.
When you accidentally clicked the opponent's piece on the board, or when there is no piece, it won't show 'wrong move'.
----------------------------------------------------------------------

As a loyal fan of you, I expect that could you please add some more functions?
Such as:
**1.Is it possible to add a 'sound/xx.mp3 or xx.wav' folder that can allow users to put in their favorite moves/catch sounds.**

**2.Add parameters that can change the color of the board in the 'settings.json' file.**
For example, I like to use
Black: R 134 G 166 B 102
White: R 255 G 255 B 221
![image](https://user-images.githubusercontent.com/88195849/130699991-c4ff0ebb-1d85-45f8-add7-43e663f503ff.png)

**3.Is it possible to design the program layout from vertical to horizontal**
because if the board is set too large, the buttons or labels below cannot be seen.
![image](https://user-images.githubusercontent.com/88195849/130700022-2462b44d-8882-4111-bf9b-22b46c9f888a.png)

**4. Is it possible to add a text box to display the question number?**
So if a user make a mistake that he may go to the database to see the correct step.
![image](https://user-images.githubusercontent.com/88195849/130700482-149dcaee-a6ef-42b8-9aa5-16f399cc43d7.png)

**5.Please put your paypal or any donation link, that we can cheer you up!**

**Comment by brianch** [comment]
Hi, 

Thanks for the support (and for the VB6 memories hehe Good luck in your studies, by the way) :)

Just an update on this, I haven't pushed the changes to the repository here yet, but I finally made the horizontal layout work (this isn't the final layout, I was just trying to make it work first):
<img src="https://user-images.githubusercontent.com/5335499/131395910-3cd11f63-5a8b-49ba-8a71-6032e51b5b5c.jpg" width="50%" height="50%">

With the design already in tabs like that, the settings (and puzzle info) will be easier to put in place now.

And thanks for creating the account, the suggestions and especially the help testing that Windows 8 issue were really appreciated.

**Comment by brianch** [comment]
Closing this as these suggestions are all implemented now
