### ISSUE TITLE
Error in the Spanish PDF translation

### ISSUE THREAD

**Issue by podcastlinux** [brianch/offline-chess-puzzles#26]
In pdf in spanish "play white" is "juegan blancas" not "brancas juegan". 
Better "juegan negras" than "negras juegan".
I use pdf puzzles with my pupils.  Thank you.

**Comment by brianch** [comment]
Thanks a lot! I fixed it.

I'm super happy to hear it's been helpful to you and your students! 😀

I think you should be able to download the updated zip from here: https://github.com/brianch/offline-chess-puzzles/actions/runs/8912006038 

If you download it from there, there's also a "minimum popularity" search term now, for PDF exports it might be very useful to get only the best puzzles.

**Comment by podcastlinux** [comment]
Thanks a lot!!!!
