### ISSUE TITLE
Make Board Flippable

### ISSUE THREAD

**Issue by Dumuzy** [brianch/offline-chess-puzzles#9]
I love this software!
And I like to do sets of puzzles with a flipped board from time to time. So as to maybe better learn what the opponent is threatening me. 
I would therefore like to have a little checkbox which makes the board flip around.  This should be on the main page. 
And maybe it should be remembered for the next time I open the program. Just for consistency, when all the other stuff is remembered.

**Comment by brianch** [comment]
I had never thought about doing puzzles looking from the opponent's perspective to be honest, perhaps it would be a nice idea for my practice sessions too hehe

It's not difficult to add but I'm not 100% sure yet on how to put this option on the interface, I'll think a bit about it, seems like a good feature to have indeed.
